name: aisstream
description: A sample AISStream command line tool.
version: 1.0.0

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
